### ISSUE TITLE
Error in verbose mode when result contains non ascii code

### ISSUE THREAD

**Issue by Patouche** [octplane/ansible_stdout_compact_logger#4]
Hi,

Thanks a lot for your work. I notice a small inconvenience using when I tried to print unicode characters. I got the problem only when I use the `-v` ansible option.

For example, if you define the following playbook :

```yaml
---
- name: "Test case for issue unicode"
  hosts: first
  tasks:
    - name: "Error when using -v"
      command: echo -e "\xe2\x98\xba\x0a"
```

This will produce the output in verbose mode  :

>  [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible.plugins.callback.anstomlog.CallbackModule object at 0x7f21b4605c90>): 'ascii'
codec can't encode character u'\u263a' in position 0: ordinal not in range(128)

Once again, thanks for you work.

Patrick
